server:
  port: 3008

spring:
  application:
    name: servicio-credito
  
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.ecommerce.credito: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info