global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3011']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'catalog-service'
    static_configs:
      - targets: ['catalog-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'transaction-service'
    static_configs:
      - targets: ['transaction-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093